name: my first workflow
on: push
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
    - name: firststep
      run: echo hello
    - name: Variable value
      run: echo ${{vars.version}}
    - name: Variable value
      run: echo ${{secrets.image_name}}
